// Code generated by protoc-gen-go.
// source: github.com/nlandolfi/mdp/mdp.proto
// DO NOT EDIT!

/*
Package mdp is a generated protocol buffer package.

It is generated from these files:
	github.com/nlandolfi/mdp/mdp.proto

It has these top-level messages:
	Vector
	Matrix
	LinearRewardFunction
*/
package mdp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values" json:"values,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Matrix struct {
	Columns []*Vector `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
}

func (m *Matrix) Reset()                    { *m = Matrix{} }
func (m *Matrix) String() string            { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()               {}
func (*Matrix) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Matrix) GetColumns() []*Vector {
	if m != nil {
		return m.Columns
	}
	return nil
}

type LinearRewardFunction struct {
	Theta *Vector `protobuf:"bytes,1,opt,name=theta" json:"theta,omitempty"`
}

func (m *LinearRewardFunction) Reset()                    { *m = LinearRewardFunction{} }
func (m *LinearRewardFunction) String() string            { return proto.CompactTextString(m) }
func (*LinearRewardFunction) ProtoMessage()               {}
func (*LinearRewardFunction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LinearRewardFunction) GetTheta() *Vector {
	if m != nil {
		return m.Theta
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector)(nil), "elos.models.Vector")
	proto.RegisterType((*Matrix)(nil), "elos.models.Matrix")
	proto.RegisterType((*LinearRewardFunction)(nil), "elos.models.LinearRewardFunction")
}

func init() { proto.RegisterFile("github.com/nlandolfi/mdp/mdp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcb, 0x49, 0xcc, 0x4b, 0xc9, 0xcf, 0x49, 0xcb,
	0xd4, 0xcf, 0x4d, 0x29, 0x00, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xee, 0xd4, 0x9c,
	0xfc, 0x62, 0xbd, 0xdc, 0xfc, 0x94, 0xd4, 0x9c, 0x62, 0x25, 0x05, 0x2e, 0xb6, 0xb0, 0xd4, 0xe4,
	0x92, 0xfc, 0x22, 0x21, 0x31, 0x2e, 0xb6, 0xb2, 0xc4, 0x9c, 0xd2, 0xd4, 0x62, 0x09, 0x46, 0x05,
	0x66, 0x0d, 0xc6, 0x20, 0x28, 0x4f, 0xc9, 0x9c, 0x8b, 0xcd, 0x37, 0xb1, 0xa4, 0x28, 0xb3, 0x42,
	0x48, 0x97, 0x8b, 0x3d, 0x39, 0x3f, 0xa7, 0x34, 0x37, 0x0f, 0xa2, 0x84, 0xdb, 0x48, 0x58, 0x0f,
	0xc9, 0x28, 0x3d, 0x88, 0x39, 0x41, 0x30, 0x35, 0x4a, 0x8e, 0x5c, 0x22, 0x3e, 0x99, 0x79, 0xa9,
	0x89, 0x45, 0x41, 0xa9, 0xe5, 0x89, 0x45, 0x29, 0x6e, 0xa5, 0x79, 0xc9, 0x25, 0x99, 0xf9, 0x79,
	0x42, 0x9a, 0x5c, 0xac, 0x25, 0x19, 0xa9, 0x25, 0x89, 0x40, 0x43, 0x18, 0x71, 0x19, 0x02, 0x51,
	0xe1, 0x24, 0x15, 0x25, 0x81, 0xcb, 0x43, 0x49, 0x6c, 0x60, 0xdf, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0x7a, 0x19, 0x03, 0xf3, 0x00, 0x00, 0x00,
}
